image: algobardo/jsraces:v1.6

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - echo "Runnning on $CI_RUNNER_DESCRIPTION"
  - npm config set cache /cache/npm-cache
  - echo "NPM cache set to /cache/npm-cache"
  - export GRADLE_USER_HOME=/cache/.gradle
  # Configuring TAJS
  - echo "desktop=false"  >> .tajsconfig
  - npm install
  - (cd ts-spec-reader && npm install && node_modules/typescript/bin/tsc --module commonjs src/*.ts)

cache:
  key: "SharedCache"
  paths:
    - $GRADLE_USER_HOME/caches/
    - $GRADLE_USER_HOME/wrapper/
    - $GRADLE_USER_HOME/build-cache/
    - ts-spec-reader/node_modules/
    - node_modules/
    - /cache/npm-cache
    
  
stages:
  - build_tajs
  - unit_tests
  - wrapup


build_tajs_task:
  stage: build_tajs
  artifacts:
    expire_in: 4 week
    when: always
    paths:
    - build
  script: 
    - gradle compileTest

######################
##### UNIT TESTS #####
######################

test_parsing:
  stage: unit_tests
  script:
  - gradle :test -i --tests "dk.webbies.tajscheck.test.TestParsing"
  - mv build/reports/tests build/reports/test_parsing
  artifacts:
    expire_in: 4 week
    paths:
    - builds/TSTAJS/TajsCheck/build/reports

test_various:
  stage: unit_tests
  script:
  - gradle :test -i --tests "dk.webbies.tajscheck.test.TestVarious"
  - mv build/reports/tests build/reports/test_various
  artifacts:
    expire_in: 4 week
    paths:
    - builds/TSTAJS/TajsCheck/build/reports

test_dynamic_benchmarks:
  stage: unit_tests
  script:
  - gradle :test -i --tests "dk.webbies.tajscheck.test.dynamic.RunBenchmarks"
  - mv build/reports/tests build/reports/test_dynamic
  artifacts:
    expire_in: 4 week
    paths:
    - builds/TSTAJS/TajsCheck/build/reports

test_dynamic_unit:
  stage: unit_tests
  script:
  - gradle :test -i --tests "dk.webbies.tajscheck.test.dynamic.UnitTests"
  - mv build/reports/tests build/reports/test_dynamic
  artifacts:
    expire_in: 4 week
    paths:
    - builds/TSTAJS/TajsCheck/build/reports

test_static_soundness:
  stage: unit_tests
  script:
  - gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.TAJSCheckerSoundness"
  - mv build/reports/tests build/reports/test_static_soundness
  artifacts:
    expire_in: 4 week
    paths:
    - builds/TSTAJS/TajsCheck/build/reports

test_static_consistency:
  stage: unit_tests
  script:
  - gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.TSTestConsistency"
  - mv build/reports/tests build/reports/test_static_soundness
  artifacts:
    expire_in: 4 week
    paths:
    - builds/TSTAJS/TajsCheck/build/reports

test_tajs:unit:
  stage: unit_tests
  script:
  - gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.TAJSUnitTests"
  - mv build/reports/tests build/reports/test_tajs_unit
  artifacts:
    expire_in: 4 week
    paths:
    - builds/TSTAJS/TajsCheck/build/reports


test_tajs:benchmarks:
  stage: unit_tests
  script:
  - gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks"
  - mv build/reports/tests build/reports/test_tajs_benchmarks
  artifacts:
    expire_in: 4 week
    paths:
    - builds/TSTAJS/TajsCheck/build/reports

test_tajs:benchmarks_tracified:
  stage: unit_tests
  script:
  - gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeTracified"
  - mv build/reports/tests build/reports/test_tajs_benchmarks_tracified
  artifacts:
    expire_in: 4 week
    paths:
    - builds/TSTAJS/TajsCheck/build/reports


wrapup_task:
  stage: wrapup
  script:
  -  echo "DONE"
  artifacts:
    expire_in: 4 week
    paths:
    - builds/TSTAJS/TajsCheck/build/reports


