image: algobardo/jsraces:v1.6

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GRADLE_OPTS: -Xmx10G

before_script:
  - echo "Runnning on $CI_RUNNER_DESCRIPTION"
  - mkdir -p cache
  - npm config set cache $PWD/cache/npm-cache
  - echo "NPM cache set to $PWD/cache/npm-cache"
  - export GRADLE_USER_HOME=$PWD/cache/.gradle
  # Configuring TAJS
  - echo "desktop=false"  >> .tajsconfig
  - npm install
  - (cd ts-spec-reader && npm install && node_modules/typescript/bin/tsc --module commonjs src/*.ts)

cache:
  key: "SharedCache"
  paths:
    - $GRADLE_USER_HOME/caches/
    - $GRADLE_USER_HOME/wrapper/
    - $GRADLE_USER_HOME/build-cache/
    - ts-spec-reader/node_modules/
    - node_modules/
    - cache/npm-cache
    
  
stages:
  - build_tajs
  - unit_tests
  - wrapup


build_tajs_task:
  stage: build_tajs
  artifacts:
    expire_in: 4 week
    when: always
    paths:
    - build
  script: 
    - gradle compileTest

######################
##### UNIT TESTS #####
######################

test_parsing:
  stage: unit_tests
  script:
  - gradle :test -i --tests "dk.webbies.tajscheck.test.TestParsing"
  - mv build/reports/tests build/reports/test_parsing
  artifacts:
    expire_in: 4 week
    paths:
    - builds/TSTAJS/TajsCheck/build/reports

test_various:
  stage: unit_tests
  script:
  - gradle :test -i --tests "dk.webbies.tajscheck.test.TestVarious"
  - mv build/reports/tests build/reports/test_various
  artifacts:
    expire_in: 4 week
    paths:
    - builds/TSTAJS/TajsCheck/build/reports

test_dynamic_benchmarks:
  stage: unit_tests
  script:
  - gradle :test -i --tests "dk.webbies.tajscheck.test.dynamic.RunBenchmarks"
  - mv build/reports/tests build/reports/test_dynamic
  artifacts:
    expire_in: 4 week
    paths:
    - builds/TSTAJS/TajsCheck/build/reports

test_dynamic_unit:
  stage: unit_tests
  script:
  - gradle :test -i --tests "dk.webbies.tajscheck.test.dynamic.UnitTests"
  - mv build/reports/tests build/reports/test_dynamic
  artifacts:
    expire_in: 4 week
    paths:
    - builds/TSTAJS/TajsCheck/build/reports

test_static_soundness:
  stage: unit_tests
  script:
  - gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.TAJSCheckerSoundness"
  - mv build/reports/tests build/reports/test_static_soundness
  artifacts:
    expire_in: 4 week
    paths:
    - builds/TSTAJS/TajsCheck/build/reports

test_static_consistency:
  stage: unit_tests
  script:
  - gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.TSTestConsistency"
  - mv build/reports/tests build/reports/test_static_soundness
  artifacts:
    expire_in: 4 week
    paths:
    - builds/TSTAJS/TajsCheck/build/reports

test_tajs:unit:
  stage: unit_tests
  script:
  - gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.TAJSUnitTests"
  - mv build/reports/tests build/reports/test_tajs_unit
  artifacts:
    expire_in: 4 week
    paths:
    - builds/TSTAJS/TajsCheck/build/reports



######################
##### BENCHMARKS #####
######################

.benchmark: &benchmarks_template
  stage: unit_tests
  allow_failure: true
  only:
    - tags
    - triggers
    - schedules
  artifacts:
    expire_in: 4 week
    when: always
    paths:
    - test/benchmarks/


benchmark_zepto:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmark[Benchmark{Zepto.js}]"

benchmark_pathjs:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmark[Benchmark{pathjs}]"

benchmark_pdf:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmark[Benchmark{PDF.js}]"

benchmark_peerjs:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmark[Benchmark{PeerJS}]"

benchmark_moment:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmark[Benchmark{Moment.js}]"

benchmark_box2dweb:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmark[Benchmark{box2dweb}]"

benchmark_hammer:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmark[Benchmark{Hammer.js}]"

benchmark_photoswipe:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmark[Benchmark{PhotoSwipe}]"

benchmark_accounting:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmark[Benchmark{accounting.js}]"

benchmark_medium:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmark[Benchmark{Medium Editor}]"

benchmark_highlight:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmark[Benchmark{highlight.js}]"

benchmark_pleasejs:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmark[Benchmark{PleaseJS}]"

benchmark_codemirror:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmark[Benchmark{CodeMirror}]"

benchmark_intro:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmark[Benchmark{intro.js}]"

benchmark_lunr:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmark[Benchmark{lunr.js}]"

benchmark_handlebars:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmark[Benchmark{Handlebars}]"

benchmark_jasmine:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmark[Benchmark{Jasmine}]"

benchmark_reveal:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmark[Benchmark{reveal.js}]"

benchmark_leaflet:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmark[Benchmark{Leaflet}]"

benchmark_redux:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmark[Benchmark{Redux}]"

benchmark_qunit:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmark[Benchmark{QUnit}]"

benchmark_knockout:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmark[Benchmark{Knockout}]"

benchmark_async:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmark[Benchmark{async}]"

benchmark_sortable:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmark[Benchmark{Sortable}]"

benchmark_swiper:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmark[Benchmark{Swiper}]"

benchmark_axios:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmark[Benchmark{axios}]"



##############################
##### BENCHMARKS PATCHED #####
##############################

.benchmark: &benchmarks_template
  stage: unit_tests
  allow_failure: true
  only:
    - tags
    - triggers
    - schedules
  artifacts:
    expire_in: 4 week
    when: always
    paths:
    - test/benchmarks/


benchmark_patched_zepto:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmarkPatched[Benchmark{Zepto.js}]"

benchmark_patched_pathjs:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmarkPatched[Benchmark{pathjs}]"

benchmark_patched_pdf:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmarkPatched[Benchmark{PDF.js}]"

benchmark_patched_peerjs:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmarkPatched[Benchmark{PeerJS}]"

benchmark_patched_moment:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmarkPatched[Benchmark{Moment.js}]"

benchmark_patched_box2dweb:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmarkPatched[Benchmark{box2dweb}]"

benchmark_patched_hammer:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmarkPatched[Benchmark{Hammer.js}]"

benchmark_patched_photoswipe:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmarkPatched[Benchmark{PhotoSwipe}]"

benchmark_patched_accounting:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmarkPatched[Benchmark{accounting.js}]"

benchmark_patched_medium:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmarkPatched[Benchmark{Medium Editor}]"

benchmark_patched_highlight:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmarkPatched[Benchmark{highlight.js}]"

benchmark_patched_pleasejs:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmarkPatched[Benchmark{PleaseJS}]"

benchmark_patched_codemirror:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmarkPatched[Benchmark{CodeMirror}]"

benchmark_patched_intro:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmarkPatched[Benchmark{intro.js}]"

benchmark_patched_lunr:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmarkPatched[Benchmark{lunr.js}]"

benchmark_patched_handlebars:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmarkPatched[Benchmark{Handlebars}]"

benchmark_patched_jasmine:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmarkPatched[Benchmark{Jasmine}]"

benchmark_patched_reveal:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmarkPatched[Benchmark{reveal.js}]"

benchmark_patched_leaflet:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmarkPatched[Benchmark{Leaflet}]"

benchmark_patched_redux:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmarkPatched[Benchmark{Redux}]"

benchmark_patched_qunit:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmarkPatched[Benchmark{QUnit}]"

benchmark_patched_knockout:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmarkPatched[Benchmark{Knockout}]"

benchmark_patched_async:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmarkPatched[Benchmark{async}]"

benchmark_patched_sortable:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmarkPatched[Benchmark{Sortable}]"

benchmark_patched_swiper:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmarkPatched[Benchmark{Swiper}]"

benchmark_patched_axios:
  <<: *benchmarks_template
  script: gradle :test -i --tests "dk.webbies.tajscheck.test.tajs.analyze.AnalyzeBenchmarks.analyzeBenchmarkPatched[Benchmark{axios}]"


######################
###### WRAP-UP #######
######################


wrapup_task:
  stage: wrapup
  when: always
  environment:
    name: $CI_COMMIT_REF_NAME
    url: http://tajscheck.casadev.cs.au.dk
  tags:
    - casadev
  script:
    - (npm install -g typescript @angular/cli && cd web-ui && npm install && npm run build)
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$CASADEV_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh -p $SCP_REMOTE_PORT $SCP_REMOTE_USER@$SCP_REMOTE_HOST "rm -r $SCP_REMOTE_FOLDER | true"
    - scp -r -P $SCP_REMOTE_PORT web-ui/dist $SCP_REMOTE_USER@$SCP_REMOTE_HOST:$SCP_REMOTE_FOLDER
    - scp -r -P $SCP_REMOTE_PORT out $SCP_REMOTE_USER@$SCP_REMOTE_HOST:$SCP_REMOTE_FOLDER/out
    - scp -r -P $SCP_REMOTE_PORT test $SCP_REMOTE_USER@$SCP_REMOTE_HOST:$SCP_REMOTE_FOLDER/test
  artifacts:
    expire_in: 4 week
    paths:
    - builds/TSTAJS/TajsCheck/build/reports


